### ISSUE TITLE
keras version?

### ISSUE THREAD

**Issue by agladstein** [flag0010/pop_gen_cnn#2]
What version of keras are you using?
I am using keras 2.2.2.

When I tried running `make.tajD.pred.py`, I got the error

```
Traceback (most recent call last):
  File "make.tajD.pred.py", line 4, in <module>
    from keras.layers import Dense, Dropout, Flatten, Merge
ImportError: cannot import name Merge
```

But, lowercase `merge` works.
```
from keras.layers import merge
```

**Comment by flag0010** [comment]
Thanks for bringing this to my attention.  The code works on Keras 2.0.6 and 2.0.8.  Perhaps more importantly, for that particular piece of code Merge is not needed.  I think I copy and pasted an import statement from some other project and forgot to omit it.  I will remove it.  Please update your copy too.
